### ISSUE TITLE
iced-coffee-script not listed in dependencies

### ISSUE THREAD

**Issue by lorenwest** [maxtaco/emergency-dns-server#3]
Thanks for this package - it's perfect for my use case.  The install had a hiccup as iced-coffee-script wasn't listed as a dependency in package.json, and I haven't yet crossed over to installing it globally :)

**Comment by lorenwest** [comment]
The readme file says it's an additional dependency for building, but I was just running.  It is required in lib/server.js.

**Comment by maxtaco** [comment]
Thanks for the bug report.  Should work now; there's a separate runtime nowadays.

**Comment by lorenwest** [comment]
:fireworks:
